import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children,modal }) {
  return (
    <html lang="en">
      <body>
        {/* Master Page Content */}
        {children}
        {/* Render Modal Dialog Content */}
        {modal}
      </body>
    </html>
  );
}
